### ISSUE TITLE
11 * bad catch type ?

### ISSUE THREAD

**Issue by dcb314** [l3ib/nitrogen#103]
SetBG.cc:677:30: warning: catching polymorphic type 'class Glib::FileError' by value [-Wcatch-value=]
Thumbview.cc:159:31: warning: catching polymorphic type 'class Gtk::IconThemeError' by value [-Wcatch-value=]
Thumbview.cc:160:31: warning: catching polymorphic type 'class Gdk::PixbufError' by value [-Wcatch-value=]
NWindow.cc:79:32: warning: catching polymorphic type 'class Gtk::IconThemeError' by value [-Wcatch-value=]
NWindow.cc:314:31: warning: catching polymorphic type 'class Gtk::IconThemeError' by value [-Wcatch-value=]
NWindow.cc:320:31: warning: catching polymorphic type 'class Gtk::IconThemeError' by value [-Wcatch-value=]
NWindow.cc:330:31: warning: catching polymorphic type 'class Gtk::IconThemeError' by value [-Wcatch-value=]
NWindow.cc:338:31: warning: catching polymorphic type 'class Gtk::IconThemeError' by value [-Wcatch-value=]
NWindow.cc:346:31: warning: catching polymorphic type 'class Gtk::IconThemeError' by value [-Wcatch-value=]
NWindow.cc:354:31: warning: catching polymorphic type 'class Gtk::IconThemeError' by value [-Wcatch-value=]
Util.cc:206:28: warning: catching polymorphic type 'class Glib::FileError' by value [-Wcatch-value=]

Suggest catch by const reference, not value.

**Comment by daf** [comment]
Thanks @dcb314!
