### ISSUE TITLE
BadDrawable (invalid Pixmap or Window parameter)

### ISSUE THREAD

**Issue by fhdk** [l3ib/nitrogen#105]
I am obviously missing something - but I can't find what it is.

[My question at Manjaro Forum](https://forum.manjaro.org/t/nitrogen-what-is-missing/31269/4)

Dual-head system:
* Manjaro
* Openbox wm 
* Running from CLI, nitrogen lists images from folder
* Select one and click **Apply** then

![select_2017-09-17-134827_636x152](https://user-images.githubusercontent.com/22748698/30520594-1da2486c-9bb1-11e7-824c-69c239c227e8.png)

Have been searching and the only advise I could find was - *Remove `.config/nitrogen` folder* - and that does not help.

So I was thinking - you might know what I am missing?

Edit: Improvement has been made
It seems the activation of two monitors using below command makes nitrogen trigger the error.

    xrandr --output VIRTUAL1 --off --output DP2 --off --output DP1 --off --output HDMI2 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VGA1 --off

Removing the command from openbox autostart removes the error and makes nitrogen work as expected. Instead of using xrandr to set the xinerama I use xfce4-settings and then nitrogen generates no errors and it is possible to set different wallpapers for each output.

**Comment by daf** [comment]
Hi @fhdk - Nitrogen goes to some lengths to re-use existing pixmaps for resource conservation - it simply tries to draw over any existing one that's being used for a background.  It probably is not robust enough to deal with a dynamically changing situation like monitors being turned on and off.  I'll try to reproduce on my setup at work and see if I can adjust properly.

**Comment by fhdk** [comment]
I have been fiddling with different settings.

I am using Manjaro and I have made some observations regarding this issue.

It all comes down to the `bg-saved.cfg` file which

When I make a clean install the live media - for obvious reasons - duplicates the monitor output.
When I use a distro like MaboxLinux or Archlabs Minimo which all have a predefined set of files which is copied from `/etc/skel` to the users `.config` folder.

With MaboxLinux the file starts with `[:0.0]` and I can setup a dual-head,  but not wallpaper for separate screens.

To be continued ... after reboot

**Comment by HarryCutts** [comment]
I just encountered this bug on Manjaro with i3. In case it helps anyone, what fixed it for me was changing the order of execution of `xrandr` and `nitrogen` in my i3 configuration. Previously, I had this in my config file:

    exec --no-startup-id nitrogen --restore; sleep 1; picom -b
    exec sh ~/.screenlayout.sh   # see below for contents

...where .screenlayout.sh contains `xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x216 --rotate normal --output HDMI1 --mode 1920x1200 --pos 1920x0 --rotate normal --output VIRTUAL1 --off --output eDP-1-2 --off --output DVI-D-1-1 --off`. Swapping these lines around fixed the problem:

    exec sh ~/.screenlayout.sh   # see below for contents
    exec --no-startup-id nitrogen --restore; sleep 1; picom -b

**Comment by fhdk** [comment]
My experience is as @HarryCutts just forgot all about it.

I don't think there is any other answers to this than making sure the order or precedence.

Just like equations - you will have to know to write it :)
