### ISSUE TITLE
Unknown root window type when using easystroke

### ISSUE THREAD

**Issue by setzer22** [l3ib/nitrogen#106]
Hi everyone,

I'm running Arch Linux and using i3 as my window manager. I use nitrogen to set the wallpaper. In my system, whenever my monitor setup changes, I execute `nitrogen --restore` in order to adapt the wallpaper to the new monitor layout. 

However, whenever I plug in some monitors, causing some specific monitor configurations, nitrogen seems to be unable to run. I get the following messages, which are repeated a lot of times:

```
UNKNOWN ROOT WINDOW TYPE DETECTED (Easystroke), please file a bug
UNKNOWN ROOT WINDOW TYPE DETECTED (Easystroke), please file a bug
UNKNOWN ROOT WINDOW TYPE DETECTED (Easystroke), please file a bug
UNKNOWN ROOT WINDOW TYPE DETECTED (Easystroke), please file a bug
(...)
WARNING: More than one Desktop window found:
        0x 2e009db   3  Easystroke
        0x 2e009df   3  Easystroke
        0x 2e009e3   3  Easystroke
        0x 2e009e7   3  Easystroke
(...)
(nitrogen:18724): GdkPixbuf-CRITICAL **: gdk_pixbuf_copy_area: assertion 'dest_y >= 0 && dest_y + height <= dest_pixbuf->height' failed

(nitrogen:18724): GdkPixbuf-CRITICAL **: gdk_pixbuf_copy_area: assertion 'dest_y >= 0 && dest_y + height <= dest_pixbuf->height' failed
```
In my system, as you can see, I am running Easystroke (https://github.com/thjaeger/easystroke), which is a gesture recognition software. It appears that easystroke may be setting itself as the root window to be able to draw over the whole screen, which is one of its functionalities.

The following script can reproduce the issue in my machine:

```
#!/bin/bash

# Right monitor: 1920x1080 (eDP1)
# Left monitor: 1366x768 (VGA1), scaled to 1.25x
xrandr --output eDP1 --auto --pos 1708x0 --scale 1x1 --output VGA1 --auto --scale 1.25x1.25 --pos 0x0
nitrogen --restore
```

Is there something that could be done about this?

**Comment by daf** [comment]
Hi @setzer22, thanks for reporting.  Nitrogen has to enumerate all windows it thinks could possibly be used for showing a background and tries to detect their types, so it requires a list of exceptions - I hadn't heard of Easystroke before so it wasn't in there.  It is now.  I don't have a timetable for a new release right now but if you're comfortable building from source, it should be fixed for you.  An alternative is to use the `--force-setter` argument if you know what environment you're in, but that's more of a debugging tool and may not be as straightforward.

**Comment by setzer22** [comment]
Hi @daf, glad to be of help! The issue is not really a problem for me as it works fine most of the time, so I will wait for the next release unless you need someone to beta-test this.

Cheers
