### ISSUE TITLE
Broken with Gnome 3.26.2 - no draw-background key

### ISSUE THREAD

**Issue by nermolov** [l3ib/nitrogen#109]
Can't set (multi monitor) wallpapers with gnome, following error occurs:

```
nik@arch-desk ~/p/nitrogen> src/nitrogen 

(nitrogen:12990): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.background' does not contain a key named 'draw-background'
fish: “src/nitrogen” terminated by signal SIGTRAP (Trace or breakpoint trap)
```

GNOME Shell 3.26.2

Nitrogen commit 592c9ccee93a47c4429d90430e46cb759b422f53

**Comment by latot** [comment]
same here with 3.22.2

**Comment by luben93** [comment]
+1 on this, GNOME Shell 3.26.2

**Comment by daf** [comment]
Added a better guarding mechanism for those who don't have this key.  Mine still has it, marked as `deprecated`.  :man_shrugging:
