### ISSUE TITLE
nitrogen doesn't work with pcmanfm-qt

### ISSUE THREAD

**Issue by tranduyhung** [l3ib/nitrogen#112]
Hi,

I use LXQT on Debian and nitrogen doesn't work, it is unable to set the wallpapers

````
$ nitrogen
UNKNOWN ROOT WINDOW TYPE DETECTED (pcmanfm-qt), please file a bug

$ nitrogen --restore
UNKNOWN ROOT WINDOW TYPE DETECTED (pcmanfm-qt), please file a bug
````

I have pcmanfm-qt 0.12.0-5 (the latest stable release at the present time). The problem exists no matter what window manager I use, I have tried openbox and xfwm4.

My nitrogen version is 1.6.1-2.

Thank you for taking a look at this issue!

**Comment by daf** [comment]
Nitrogen does not yet support pcmanfm-qt - I didn't even know it existed!  There is existing support for pcmanfm, but a quick look at pcmanfm-qt's source leads me to believe it's unlikely to work, but you can try with `nitrogen --force-setter=pcmanfm` - let me know if this works for you.  Otherwise, will have to build support for it.

**Comment by tranduyhung** [comment]
`nitrogen --force-setter=pcmanfm` doesn't help, I still get the same error and setting wallpaper still doesn't work.

LXDE has been switching from GTK to QT, LXQt is the result. pcmanfm-qt is the QT version of pcmanfm, I haven't looked at the sources but I believe they are mostly different.

**Comment by tranduyhung** [comment]
Thanks @jubalh  that works! Forgot that Desktop module, it also cause similar problem with conky.

As I knew pcman said he would drop support for GTK/LXDE in future and only focus on the QT version, maybe he's changed his mind recently.

**Comment by v-fox** [comment]
This broke on some updates in LXQt/pcmanfm-qt. Now it says that it set the wallpaper but screens remain black. Adding `--force-setter=pcmanfm` results in message `UNKNOWN ROOT WINDOW TYPE DETECTED (pcmanfm-qt), please file a bug` if pcmanfm-qt runs, without it - nothing changes at all, it doesn't even say that wallpaper was selected.
