### ISSUE TITLE
Restore fails when single saved xinerama screen differs from actual screen after restart

### ISSUE THREAD

**Issue by warptozero** [l3ib/nitrogen#126]
Sometimes after switching an external display multiple times in a session the main screen ends up as xin_1. When you then set a wallpaper to that single screen, restore fails on the next restart because the main screen is then xin_0 again and `bg-saved.cfg` only contains an entry for xin_1.

Not sure why or when xinerama decides to shuffle the screen numbers, but I do run into this situation occasionally.

BTW, I don't have any expectations of how this should be handled by nitrogen, because ignoring screen id when there is only a single screen active and in `bg-saved.cfg` might not be desirable in every case. And keeping track of what xinerama does seems like it might be a really hard thing to do.

**Comment by daf** [comment]
Yes, unfortunately a limitation with how I picked to store the config stuff over a decade ago.  The real approach to fix this is #72 - store by either output name, or by EDID or something similar.  I think output name is a decent compromise but might as well think of a way to extend that further for say a laptop user who has different externals between home and work or whatever.  

Going to close this in favor of #72, please follow along there for updates!
