### ISSUE TITLE
Nitrogen --restore does not work on AwesomeWM

### ISSUE THREAD

**Issue by MCotocel** [l3ib/nitrogen#142]
Running `nitrogen --restore` on AwesomeWM gives the error:
```
UNKNOWN ROOT WINDOW TYPE DETECTED (awesome), please file a bug
```
and does not restore the wallpaper. Setting the wallpaper manually (through `nitrogen --set-scaled ~/Wallpaper/Wallpaper.jpg`) also gives this error, but successfully sets the wallpaper.

**Comment by daf** [comment]
Hi @MCotocel - I've tried to replicate this bug on a very vanilla AwesomeWM setup but haven't been able to see this behavior.  It doesn't seem like AwesomeWM usually does a synthetic root window, which is what Nitrogen is trying to detect here (think Nautilus drawing the desktop to have icons etc).  What version of AwesomeWM are you using, and is your config available anywhere?  Are you using something like https://github.com/lcpz/awesome-freedesktop?

Can you also do `xprop`, click on the desktop area, and paste the results?

I'm going to guess that the best resolution for Nitrogen is to simply ignore this `awesome` root window and hope that it is safely ignorable, but I'd like to reproduce before I make a wild assumption here.

You can also set using the normal XWindow based setter by having `--force-setter xwindows` on your nitrogen command line, and if that works, it's likely that we can just say this root window type can be ignored.

**Comment by MCotocel** [comment]
I'm using AwesomeWM directly from git. My config is located [here](https://github.com/MCotocel/linux-dotfiles/tree/unstable/home/user/.config/awesome). Running `xprop` and clicking on the desktop area gives me

```
_NET_ACTIVE_WINDOW(WINDOW): window id # 0xe0000e
_NET_CLIENT_LIST(WINDOW): window id # 0xe0000e
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0xe0000e
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 9
_NET_DESKTOP_NAMES(UTF8_STRING) = "1", "2", "3", "4", "5", "6", "7", "8", "9"
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x400005
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_SUPPORTING_WM_CHECK, _NET_STARTUP_ID, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_NUMBER_OF_DESKTOPS, _NET_CURRENT_DESKTOP, _NET_DESKTOP_NAMES, _NET_ACTIVE_WINDOW, _NET_CLOSE_WINDOW, _NET_FRAME_EXTENTS, _NET_WM_NAME, _NET_WM_STRUT_PARTIAL, _NET_WM_ICON_NAME, _NET_WM_VISIBLE_ICON_NAME, _NET_WM_DESKTOP, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU, _NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_COMBO, _NET_WM_WINDOW_TYPE_DND, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_ICON, _NET_WM_PID, _NET_WM_STATE, _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_MODAL, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_DEMANDS_ATTENTION
RESOURCE_MANAGER(STRING) = "*background:\t#1F252A\n*color0:\t#1F252A\n*color1:\t#FF8080\n*color10:\t#BEF8C1\n*color11:\t#FCFBA6\n*color12:\t#ACE1FF\n*color13:\t#D8A8FF\n*color14:\t#A2FFEB\n*color15:\t#FFFFFF\n*color2:\t#97D59B\n*color3:\t#FFFE80\n*color4:\t#80D1FF\n*color5:\t#C780FF\n*color6:\t#80FFE4\n*color7:\t#D5D5D5\n*color8:\t#1F252A\n*color9:\t#FFAEAE\n*foreground:\t#D5D5D5\nURxvt.boldFont:\txft:Iosevka:size=11\nURxvt.boldItalicfont:\txft:Iosevka:size=11\nURxvt.cursorBlink:\ttrue\nURxvt.cursorUnderline:\tfalse\nURxvt.depth:\t24\nURxvt.font:\txft:Iosevka:size=11\nURxvt.geometry:\t92x24\nURxvt.internalBorder:\t24\nURxvt.iso14755:\tfalse\nURxvt.italicFont:\txft:Iosevka:size=11\nURxvt.letterSpace:\t0\nURxvt.lineSpace:\t0\nURxvt.perl-ext-common:\t\"default, -searchable-scrollback\"\nURxvt.saveline:\t2048\nURxvt.scrollBar:\tfalse\nURxvt.scrollBar_right:\tfalse\nURxvt.urgentOnBell:\ttrue\n"
GDK_VISUALS(INTEGER) = 804, 1222
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 2
```

Running nitrogen with `--force-setter=windows` (`nitrogen --restore --force-setter=xwindows`) gives me an exit code of 0, but does nothing to the wallpaper. `nitrogen --restore --force-setter=xinerama` seems to work

**Comment by daf** [comment]
Thanks for the info!  Having your config helped - I was able to find the window in question.  It's the status bar on the bottom, which seems like the result of some widget drawing piece inside of awesome (`drawin`).  In the context of Nitrogen it can safely be ignored just like a conky window.  I've pushed a commit to master to that effect.
