### ISSUE TITLE
BadDrawable when trying to set a wallpaper

### ISSUE THREAD

**Issue by alexpetrean80** [l3ib/nitrogen#146]
The program 'nitrogen' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 120 error_code 9 request_code 62 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

OS: Endeavour OS
Nitrogen build: 1.6.1-3

This issue appears everytime I try to set a wallpaper. Wallpapers were previously set and restored on every startup (nitrogen --restore set in bspwmrc), but after the latest update as of today it fails.

**Comment by leofleeo** [comment]
Exact same thing happens to me
de: awesome
wm: awesome
dm: gdm
distro: endeavour os

**Comment by vinay-keshava** [comment]
Same issue with Awesome window manager on running `nitrogen --restore` on awesome
running nitrogen from cli fails to set wallpaper too

**Comment by vinay-keshava** [comment]
> Same issue with Awesome window manager on running `nitrogen --restore` on awesome running nitrogen from cli fails to set wallpaper too


Restarting the machine did work later
