### ISSUE TITLE
Where to find current background file path used by nitrogen?

### ISSUE THREAD

**Issue by iamtalhaasghar** [l3ib/nitrogen#150]
I don't see any command line argument to fetch the current background file path used by nitrogen. 
It would be very helpful in certain scenarios to have this option and then one can play around with it in his/her shell scripts.

Of course we can query desktop environment for this purpose but we don't have this facility for window managers like i3wm.

**Comment by napcok** [comment]
`grep file "$HOME"/.config/nitrogen/bg-saved.cfg | cut -d'=' -f2`
