### ISSUE TITLE
New Image Loading

### ISSUE THREAD

**Issue by priyanshoon** [l3ib/nitrogen#164]
It works fine btw, but whenever I download new image/wallpaper in my config directory I have to restart the nitrogen every time to load that img on nitrogen screen. This could be fix I think. 
Thank You!

**Comment by MatanzaBR** [comment]
1- What Linux distribution are you using?

2- What graphical interface are you using? 

Ex: Fluxbox, OpenBox ...

3- Does this problem repeat on a new user account?


**Wallpaper**

I use the: /usr/share/backgrounds and ~/Imagens folders

**Comment by priyanshoon** [comment]
>1- What Linux distribution are you using?
PopOS and Debian
>2- What graphical interface are you using?
X11 and i3
>3- Does this problem repeat on a new user account?
Never tried

https://github.com/l3ib/nitrogen/assets/62681950/5545f859-85b7-44d3-ad4a-f9aa0b900076

Like I said I have to restart nitrogen every time I download a image

**Comment by priyanshoon** [comment]
I closed this because I have been using older version provided by apt. I just tried using the release version 1.6.1 and it worked fine. Sorry for the bother, PEACE.
