### ISSUE TITLE
Feature request: add option --sort alpha to configuration file

### ISSUE THREAD

**Issue by Unia** [l3ib/nitrogen#23]
Hello,

Excuse me for opening two new issues quickly after one another. I could've put this in the previous one I opened, but it's something completely different and probably way easier too.

I would like Nitrogen to sort the images on alphabetical order, but I can't permanently add this to Nitrogen's configuration file. Could this please be made possible, so I won't have to type this everytime? (I know I could use a bash function, but to have this possibility native in Nitrogen would be alot better!)

Again, I look forward on hearing your thoughts on this.

**Comment by daf** [comment]
This is now in.
