### ISSUE TITLE
More useful exit warning message

### ISSUE THREAD

**Issue by jameh** [l3ib/nitrogen#32]
Currently, when a background is previewed and not applied, clicking the close button brings up this message:
![2013-07-20-191705_507x124_scrot](https://f.cloud.github.com/assets/1538657/830999/843bd796-f192-11e2-8d7f-405a5bc6c69e.png)
"You previewed an image without applying it, exit anyway?" N/y
where the close window button does the same thing as the "Yes" button

I believe a more intuitive (classic), and useful dialogue would be:
"You previewed an image without applying it, apply?" Y/n
where the close window button cancels the exit, without applying;
the Yes button continues the exit, after applying;
the No button continues the exit, without applying

i.e. the behaviour is identical to the classic "You have unsaved changes, save?" Y/n dialogue.

**Comment by daf** [comment]
Fixed in #33
