### ISSUE TITLE
Background set prior to initial Nitrogen launch not preserved

### ISSUE THREAD

**Issue by jameh** [l3ib/nitrogen#36]
It would be good if on startup, Nitrogen stored the current state of the desktop to use for example as a fallback in the case discussed in #34 of (no config file->preview background->delete window->"No" to apply changes dialog)

This case happens in general on first launch of Nitrogen if the user chooses "No" to the apply dialog.

I don't know how feasible this is.

**Comment by daf** [comment]
Just like #34, as of 53135f05b97, the initial background prior to Nitrogen's launch is preserved and restored.  The previous background does not need to be set with Nitrogen in the first place - it will just read whatever's currently there, set by any application.

This needs testing.  I've only had a chance on Xinerama setups so far.
