### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by JamesWrigley** [l3ib/nitrogen#39]
Hi there,
I'm packaging nitrogen for fedora and during the review process it was noted that the latest stable release is from 2011. Would it be possible to make a new release?

Thanks,
JamesNZ

**Comment by romildo** [comment]
It would be very nice if a new release is made available. Current one is from 2011.

**Comment by Stebalien** [comment]
*cough* Is there any reason not to just cut a release as-is (I'd like a release that includes #30)?

**Comment by daf** [comment]
I suppose there isn't - was a case of ever moving goalposts.  I'll step it up this week.

**Comment by Stebalien** [comment]
![](http://static.tvtropes.org/pmwiki/pub/images/7582720_4794.jpg)

**Comment by gfa** [comment]
are you closer to cut a release? i'm about to package the current git master as debian release 1.5.2+git20161111.0ea40c8

thanks!

**Comment by daf** [comment]
@gfa yes, 1.6.0 due extremely soon.  (I know, I know, I've been saying it.  Just need to compile these lengthy release notes)

**Comment by daf** [comment]
https://github.com/l3ib/nitrogen/releases/tag/1.6.0

![tumblr_nympy00dto1tpri36o1_500](https://cloud.githubusercontent.com/assets/228715/20247306/f918d4c8-a996-11e6-890b-bd032cd44dd0.gif)
