### ISSUE TITLE
Nitrogen not working under Gnome 3

### ISSUE THREAD

**Issue by JamesWrigley** [l3ib/nitrogen#40]
Hi there,
Nitrogen does not work with Gnome 3 on Fedora 19, applying a wallpaper doesn't do anything.

Thanks,
James W

**Comment by cookiengineer** [comment]
I was using the latest version of nitrogen today; this is not fixed.

GNOME version: 3.22.2+ (and later, tested and verified)
Multi-Monitor setup: 2x 1920x1080 + 1x 1280x1024

Same behaviour as initially described. Nitrogen started, selected wallpapers and did nothing when using either of `Apply` or running `nitrogen --restore` afterwards. Also tried selecting a wallpaper for one monitor especially; but did change nothing either.
