### ISSUE TITLE
`nitrogen --restore` does not work if one of the external monitors is disconnected.

### ISSUE THREAD

**Issue by denilsonsa** [l3ib/nitrogen#55]
How to reproduce:

1. Use `xrandr` (or `arandr`) to setup a second monitor.
2. Use `nitrogen` to set a different wallpaper (or the same one) for each of your 2 screens.
3. Run `nitrogen --restore`. It works.
4. Now disable your second monitor, so that you have only one screen.
5. Run `nitrogen --restore`. It fails because it can't find the second monitor.

Expected: it should gracefully ignore non-connected screens. Optionally, it could print a message saying that such screen was being ignored.

It is worth noting that, in my config file, the first item was number 1, and the second was number 0. I haven't tried if the order is different, and the order should alter the behavior.

**Comment by daf** [comment]
I'm not too familiar with using xrandr to enable/disable monitors - does this use Xinerama/TwinView or regular independent X displays?

**Comment by denilsonsa** [comment]
It uses Xinerama. I'm using a laptop with intel CPU and videocard.
Since it is a laptop, disconnecting and reconnecting an external monitor is a common use-case.

**Comment by daf** [comment]
Yeah, I know what's causing it then.  In the config file, for Xinerama, it uses `xin_0`, `xin_1`, etc for the keys, and I bet the API isn't reporting them in the expected order or similar.  Maybe even omitting 0.

I've actually just received a laptop from work (my first in many years), so I'll be able to replicate soon.

**Comment by daf** [comment]
@denilsonsa Please give this fix a try if you can.  The code was only considering Xinerama if there was more than one screen available - it's been relaxed now.  It might affect non-xinerama setups, but I don't have a working setup in that mode anymore and kind of think most of the userbase also wouldn't.

**Comment by denilsonsa** [comment]
I can confirm, this is fixed. Thanks!
