### ISSUE TITLE
Error when setting new background

### ISSUE THREAD

**Issue by Samuel88** [l3ib/nitrogen#59]
I compile last git version nitrogen and compilation work fine, but when I click on Apply button for the selected background image, the program close unexpectly

    (nitrogen:13960): Gtk-CRITICAL **: gtk_list_store_get_value: assertion 'VALID_ITER (iter, list_store)' failed
    (nitrogen:13960): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed
    (nitrogen:13960): GLib-GObject-CRITICAL **: g_value_unset: assertion 'G_IS_VALUE (value)' failed
    (nitrogen:13960): glibmm-ERROR **: 
    unhandled exception (type std::exception) in signal handler:
    what: basic_string::assign: __pos (which is 18446744073709551615) > this->size() (which is 0)
    Rilevato trace/breakpoint

**Comment by daf** [comment]
Thanks @Samuel88, I was finally able to replicate this issue on my laptop.  There was a change to how Xinerama based setups were detected and was trying to use an unknown desktop number to set a background with.  Please give master a try again and make sure it solves it for you - I'll test on my other setups too.
