### ISSUE TITLE
nitrogen main field blank on gubuntu 15.10

### ISSUE THREAD

**Issue by Bercio** [l3ib/nitrogen#60]
it looks like this: 
![screenshot from 2015-11-29 20-05-35](https://cloud.githubusercontent.com/assets/3931668/11459339/a7530724-96d4-11e5-9389-530400889f1f.png)

**Comment by daf** [comment]
@Bercio, looks like you didn't run it in a directory where images exist, or set up your "library" via the Preferences tab - try those out and see if you have more luck.

**Comment by Bercio** [comment]
Yeah thanks, sorry for the dumb question
