### ISSUE TITLE
nitrogen not working on gubuntu 15.10 

### ISSUE THREAD

**Issue by Bercio** [l3ib/nitrogen#61]
I've disabled icons on desktop with gnome-tweak-tools but clicking apply on nitrogen doesn't change wallpapers. I can see the wallpaper I've selected with nitrogen flashing briefly when I switch on and off the option "icons on desktop" in gnome-tweak-tools, but that's the only effect I get.

**Comment by daf** [comment]
I'll have to install it locally and see if I can reproduce.  In the meantime, are you comfortable compiling from source?  If you can, `./configure --enable-debug`, `make`, and paste the output when starting up `./src/nitrogen` (and maybe previewing one background via doubleclick).

I should really make it create a logfile without needing the debug flag... another day.

**Comment by Bercio** [comment]
I've tried but I get some error about not having having found glib-2.0 package

**Comment by daf** [comment]
Have you installed `-dev` version of all those packages?  It's a lengthy list, and one I've not fully put together at any point.  Wonder if there is a metapackage that brings them all together.

**Comment by JamesWrigley** [comment]
Try `apt-get build-dep nitrogen`.

**Comment by Bercio** [comment]
all I get is

```
MARK: nitrogen: root window type 4

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/04/05/DSC_4760.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4768.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4769.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4770.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4771.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4773.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4774.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4775.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4776.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4777.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4778.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4779.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4781.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4782.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4783.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4784.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4785.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4786.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4787.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4788.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4789.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4790.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/18/DSC_4791.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/19/DSC_4792.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/19/DSC_4794.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/19/DSC_4795.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/19/DSC_4796.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/07/19/DSC_4797.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/11/29/DSC_4803.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/11/29/DSC_4804.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/2015/11/29/DSC_4807.JPG

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/Screenshot from 2015-07-01 03:43:27.png

MARK: nitrogen: create_cache_images(): + Caching file /home/bercio/Pictures/Screenshot from 2015-10-22 01:48:03.png


(nitrogen:13194): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;
```

which doesn't seem to indicate any significant problem

**Comment by daf** [comment]
I was only interested in `MARK: nitrogen: root window type 4`, which is only output via that debug mode.  It means it's detecting the root window as Xinerama, which should be correct when icons on desktop is set off, but like I said I'll need to reproduce locally.  Sounds like there's still something drawing the Nautilus desktop, maybe a behavior change in a newer version.

**Comment by Bercio** [comment]
a93664f didn't fix it for me, I've compiled the master version in debug mode and it still outputs MARK: nitrogen: root window type 4

**Comment by daf** [comment]
Argh, ok.

Can you post the output of both `xprop -root` and `xprop` (then click on where the background is currently).  The `-root` one may be large, consider using http://gist.github.com/.

**Comment by Bercio** [comment]
<script src="https://gist.github.com/Bercio/b6ad39b895e757cce39a.js
"></script>

xprop returns WM_NAME(STRING) = "mutter guard window"


Lorenzo

**Comment by daf** [comment]
Hmm, that's exactly what a93664f is supposed to detect - and does so on my testing VM.  Can you `make clean` and remake, to ensure it really got the new code in there?

**Comment by Bercio** [comment]
actually now pretty weirdly it doesn't recognize the second screen. I can only set one background for both displays. root window type 1 now.

**Comment by daf** [comment]
Ok, type 1 is correct, good, we've got that part sorted.

In years past, GNOME had no concept of per-monitor backgrounds, so Nitrogen would only be able to set the one background.  I'm assuming Mutter is similar, but my testing environment was a VM so not multimonitored.  I'll have to test it out on a full setup to see what options are native and what Nitrogen can do to emulate.  I'll close this for now until I can confirm it's an issue or if it's just a limitation.
