### ISSUE TITLE
Set wallpaper to specific display/monitor?

### ISSUE THREAD

**Issue by welpo** [l3ib/nitrogen#62]
Looking at the documentation I could find + asking around I couldn't find a way, from command line, to set a wallpaper only for a specific display/monitor.

Is there a way to do this? I wrote a script that rewrites the file used to `--restore` in ~/.config/nitrogen/ as a workaround, but I'd like to know whether I'm missing an existing option.

If this option doesn't exist, consider this a request/suggestion to add it.

**Comment by daf** [comment]
Hi @welpo, there is a way - you can specify `--head=<x>` on the command line.  It should work with both the `--set-<mode>` and `--restore` flags.  Hopefully this addresses what you need it to do.

The documentation is long out of date, I've yet to get to cleaning it up (see #20), but is one of the last things to do before 1.6 is released.

**Comment by welpo** [comment]
Hi @daf,
I tried the following:
`nitrogen --head=1 '~/Pictures/wallpaper.png'` but I got:
`Error parsing command line: Unexpected argument head`

I'm running the version from the Debian stable repo, 1.5.2-2.

**Comment by daf** [comment]
Ah, that's why - forgot to mention this isn't in a release yet.  If you're comfortable compiling from source, it'll be there - otherwise, please wait for 1.6 to be released.
