### ISSUE TITLE
Nitrogen does not build with l10n

### ISSUE THREAD

**Issue by Vladimir-csp** [l3ib/nitrogen#64]
L10n not compiled when building Nitrogen.

```
autoreconf -fi
./configure
make
...
Making all in po
make[3]: Entering directory '/tmp/nitrogen/nitrogen-master/po'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/tmp/nitrogen/nitrogen-master/po'
```

How do I build with l10n?

**Comment by dglava** [comment]
Would it be possible to look into this? It's a bummer having all those translations, but them not being built/installed.

**Comment by daf** [comment]
I will look into it - unfortunately it's one of those things I set up years ago and completely forgot how it works.  Hopefully I followed the right standardized setup and can get it going again.

**Comment by daf** [comment]
The missing piece was the `po/LINGUAS` file.   In order to get the .po files to build and install locally, seems you have to use `make dist`, and I can't tell why.
