### ISSUE TITLE
Feature Request: add --random function

### ISSUE THREAD

**Issue by berseker** [l3ib/nitrogen#7]
Dears, 

I'm using nitrogen with my compiz-standalone system and that's great

I would like to see if possible a sort of "random" function implemented..
let's say, I have now a directory full of wallpapers, on autostart script I have now "nitrogen --restore" that applies last wallpaper I selected and "applied" with the apply button. I would like however at every start, a different wallpaper loaded from the directory (ies) I have setup in nitrogen itself.. can this be implemented?

**Comment by daf** [comment]
Four years almost to the day, this is implemented! (in 72acc82)

On the command line, you can use `nitrogen --set-auto --random` to have it use your configuration stored directories, or specify a dir to have it use that.

In the GUI, `Ctrl+R` will randomly pick a bg from the existing list using whatever mode/screen/bg color are configured.

**Comment by freed00m** [comment]
Hi, there is no clear info in `--help` that states that `--random` has to be used with `--set-*` flag. I had to dig this issue just to see why standalone `--random` doesn't do nothing.

**Comment by obirn** [comment]
> `random`

me too... I had to dig so far, still 5 years later lol.
