### ISSUE TITLE
Install to $PREFIX

### ISSUE THREAD

**Issue by guhcampos** [l3ib/nitrogen#70]
Hi guys,

I noticed that even if I do a "./configure --prefix=$HOME", nitrogen's makefile tries to install some files in /usr/share/:

Steps to Reproduce (this was RHEL7):

[gustavo@hostname nitrogen]$./configure --prefix=$HOME/.local > /dev/null && make -j 8 > /dev/null && make install > /dev/null
./configure: line 3781: ++: command not found
gtk-update-icon-cache: Cache file created successfully.
/bin/install: cannot create regular file ‘/usr/share/appdata/nitrogen.appdata.xml’: Permission denied
make[3]: **\* [install-appdataDATA] Error 1
make[2]: **\* [install-am] Error 2
make[1]: **\* [install-recursive] Error 1
make: **\* [install-recursive] Error 1

**Comment by berkley4** [comment]
I ran into a similar issue when trying to install to /usr/local. The solution appears to be to edit line 3 in data/Makefile.am as below...

-appdatadir = /usr/share/appdata
+appdatadir = $(datarootdir)/appdata

**Comment by daf** [comment]
Awesome, thanks @berkley4, will verify!
