### ISSUE TITLE
CLI option to select monitor

### ISSUE THREAD

**Issue by Vladimir-csp** [l3ib/nitrogen#71]
Please add a way to select monitor when setting wallpaper from CLI.
Something like `--monitor` option which would take number or output name:

```
nitrogen --set-auto image.png --monitor 1
nitrogen --set-tiled image2.jpg --monitor LVDS1
```

**Comment by Vladimir-csp** [comment]
This could also be extended into background setter that would work via MIME associations (think 'open with' menu in file manager)
It may require `--monitor` option to take a keyword like `choose` in which case nitrogen would ask user to select monitor by dialog window if there are more than one monitor active.

**Comment by AppleSeed2010** [comment]
Hi,
there is a way to select screen with the option --head :

> nitrogen --head=0 --set-zoom img1.jpg # for first screen
> nitrogen --head=1 --set-zoom-fill img2.jpg # for second screen
> nitrogen --head=X --set-scaled imgY.jpg # etc...

You need to add a zoom option (scale or other) or the UI will pop with an error message in bash.
Work with the current git version.
