### ISSUE TITLE
Conflict with conky

### ISSUE THREAD

**Issue by Vladimir-csp** [l3ib/nitrogen#76]
If conky is being run with `own_window_type = 'desktop'`, nitrogen fails to recognize multimonitor setup:

```
UNKNOWN ROOT WINDOW TYPE DETECTED, will attempt to set via normal X procedure
```

`--restore` sets single wallpaper across all desktops, main window does not show display selection.

**Comment by daf** [comment]
I now understand this issue!  Closing in favor of #88 and shipping in 1.6.1.
