### ISSUE TITLE
Gnome 3.20 Draws over nitrogen

### ISSUE THREAD

**Issue by Flat** [l3ib/nitrogen#78]
Using Gnome-Shell 3.20 gnome draws wallpapers over nitrogen's, with seemingly no way to disable Gnome's wallpapers, even using gnome-tweak-tool or dconf-editor

**Comment by ikeydoherty** [comment]
GNOME Shell doesn't provide a root xwin, it draws using FBOs via Mutter. i.e. its not an actual window that one can draw over. I doubt there is anything that Nitrogen can do in this respect, given that it specifically draws over the XWindow. 

You'd have to use something that provides a root window, typically this is achieved by running a file manager like Nautilus or Nemo, and allowing it to display desktop icons (GNOME Tweak Tool is your friend here)

**Comment by Flat** [comment]
Even when running Nautilus Nitrogen does not properly draw over it. I am not as well versed in the land of how desktop wallpapers work as I assume you are, however even when running Nautilus, it provides it's own xwindow instead of using the root 0 window. You _can_ draw over this Nautilus window, but in my opinion it would make more sense to overwrite how Mutter originally does it, or to use gsettings to change the gnome wallpaper.

**Comment by ikeydoherty** [comment]
gsettings would be the most portable way of doing it, yes.

**Comment by daf** [comment]
This is indeed how it is done in Nitrogen, see [SetBG.cc](https://github.com/l3ib/nitrogen/blob/34df91332cfff37875ee9f1372916b545fe902d5/src/SetBG.cc#L1131-L1155).

Typically when these stop working it's because the detection mechanism for finding these fake desktop windows is broken - in the past the class names have changed, or the gsettings keys change, etc...  I don't run these environments myself and have a non-existant test-suite for all the possible combinations so I miss when things change.

I've just recently learned how to run DEs inside of docker and show them with Xephyr so hopefully this will improve, and I'll look into this specific issue.

**Comment by Flat** [comment]
After updating to git master, the wallpaper is currently correctly set via gsettings; Nitrogen crashes with ```(nitrogen:7522): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.background' does not contain a key named 'draw-background'``` after setting the background however. I also appear to have lost support for setting wallpapers separately by monitor (The main reason for using Nitrogen), I am unsure if that is a separate bug or intentional on gnome/mutter though. It appears Arch Linux's nitrogen package is from the last "release" from 2011, which would explain the lack of actually setting the wallpaper. Nitrogen is also missing a picture-options ```wallpaper``` key that allows gnome/mutter to span an image correctly across monitors.

**Comment by daf** [comment]
Had to add yet another mechanism to detect Mutter and correctly figure out if GNOME is running, but seems to be working with a modern GNOME setup.

@Flat 
> Nitrogen is also missing a picture-options wallpaper key that allows gnome/mutter to span an image correctly across monitors.

While testing this, I discovered that the Tiled option in Nitrogen's dropdown sets the key to `wallpaper` - and I think it's accurate from what I'm seeing.  `wallpaper` does indeed let an image span multiple monitors but leaves seams where the image repeats.  I think I was expecting something more akin to zoom-fill mode in Nitrogen's native set modes.  Not sure I can do anything else here.

**Comment by daf** [comment]
Hmm, I see a reference to a picture-options mode named `spanned` that may be correct, but looks absolutely terrible on my home setup, but lots of things do because I've got a mixed 4k/non-4k multimonitor setup now.  I'll see if I can get it on my work machine.

**Comment by daf** [comment]
May have just been my test image.  Going to add `spanned` to map to "Zoomed Fill" mode.

**Comment by Flat** [comment]
Looks like it's working to set it now for me at least. On clicking apply nitrogen crashes with
```
(nitrogen:31043): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.background' does not contain a key named 'draw-background'
[1]    31043 trace trap (core dumped)  nitrogen
```
however.

Also, is there a way to set wallpaper by monitor with the GUI or has that been removed since 1.5.2?

**Comment by jwhipp** [comment]
This still isn't working, I don't get a crash but the wallpaper isn't changed.

**Comment by milouse** [comment]
@Flat I've the same problem, it looks like #43 should be re-opened on gnome 3.26+ :(

**Comment by daf** [comment]
I'll reopen #43.
