### ISSUE TITLE
signed release tarball

### ISSUE THREAD

**Issue by eworm-de** [l3ib/nitrogen#83]
Having source tarball without signature (located on a server without encryption) of bad for verification. Please provide gpg/pgp signatures for release tarballs.

**Comment by daf** [comment]
I think I've done this correctly (it's new to me): http://projects.l3ib.org/nitrogen/files/nitrogen-1.6.1.pgp.txt

**Comment by eworm-de** [comment]
First of all: Thanks a lot!

Two notes, though:
* Usually for armored signatures you just append the extension `.asc`. So for a file `nitrogen-1.6.1.tar.gz` the signature should be named `nitrogen-1.6.1.tar.gz.asc`.
* To verify a signature you need the public key. I could not find yours. So please upload your public key to a keyserver or place it on your website.

**Comment by daf** [comment]
I'm using my keybase.io account for this (https://keybase.io/daf) - I just exported my GPG key from it, it can be found at http://files.minuslab.net/daf.asc.

I'll rename the other files, thanks, I knew there was some sort of pattern.

**Comment by eworm-de** [comment]
Ok, that's fine as well. You should still link the public key from your website and/or github release page so people can find the key.

However... The tarballs from github and project page differ and the signature does not match either of both.

**Comment by daf** [comment]
Sorry, this process is still new for me.  The tarballs from projects.minuslab.net and the github release attachment seem exactly teh same to me, verified via `sha1sum` - note this is not the automatic github provided "Source code (tar/gz)" link.   Are you seeing differently?

I am indeed getting a bad verification from gpg, still learning how to do all of this.  I'll keep plugging away at it.  Thanks for your help.

**Comment by daf** [comment]
Looking at shell history, I see that I'm an idiot - generated the signature from 1.6.0's tarball.  Ugh.  I've uploaded the new version to both the project webpage and the github release page.

However, one of my machines verifies it as good, the other one says it is a bad signature.  Let me know what you see.

**Comment by eworm-de** [comment]
For me the signature is still bad. To make sure... The correct sha1sum for the tarball is `cc485fc2865939a9664d4901adbd9c1f6729dd17`?

**Comment by daf** [comment]
Yes, this is correct.  I've just redone the key, again, and seems to be working on three of my machines.  Please verify when you have a chance, thank you!

**Comment by eworm-de** [comment]
Yes, that one looks good! At lease the file I found on the project page... The file from github differs and needs to be replaced.
Thanks a lot!

**Comment by daf** [comment]
Fixed, thanks again for your help!
