### ISSUE TITLE
GPG key not on a keyserver

### ISSUE THREAD

**Issue by NicoHood** [l3ib/nitrogen#97]
You gpg key is not on a keyserver. Could you please upload it?
f40213707b7a3be87e556f65521cef8795bd91afda13dfac8f00c3550375837d

**Comment by daf** [comment]
I just added it to pgp.mit.edu, hopefully this will propagate.  Please comment later if you do not end up seeing it.

**Comment by NicoHood** [comment]
Can you please give me the fingerprint of the uploaded key? Or tell me where to find it? I could not find the key that is listed in the arch PKGBUILD here:
https://pgp.mit.edu/

Beside posting your (full) fingerprint here, you should possibly also add it below the signature here:
http://projects.l3ib.org/nitrogen/

**Comment by daf** [comment]
@NicoHood I've posted it at http://files.minuslab.net/daf.asc, it's the PGP export from my keybase.io account (https://keybase.io/daf).  This is all pretty new to me, I'm sorry for the trouble.

**Comment by NicoHood** [comment]
Your fingerprint is:
5B8B00633A07437835C80B7F1E39A08EDAB8F316

Its also found on the keyservers.

However I am wondering why the arch PKGBUILD uses a different key for source validation:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/nitrogen

Did you switch the key?

**Comment by daf** [comment]
We had a bit of a back and forth trying to get a correct/working signature in place (see #83), so the signature of the tarball itself did change a few times, perhaps it was packaged before we got it correct.

**Comment by NicoHood** [comment]
Oh. I used the sha256sum. My fault. Thanks for uploading the key. You should publish the fingerprint as mentioned on the website and all will be fine :) Thanks for signing releases ;)

**Comment by daf** [comment]
Thanks, will do!
